### ISSUE TITLE
Add default picture in project

### ISSUE THREAD

**Issue by nikitafreez** [Korelsskiy/Korelskiy.AspJavascript#1]
https://github.com/Korelsskiy/Korelskiy.AspJavascript/blob/dc043e6120d6ac53b2b3a025f6d0ec1f830fb60f/Korelskiy.AspJavascript/wwwroot/js/test1js.js#L23
Add here a default picture for the best UX

**Comment by Korelsskiy** [comment]
Разрешаю)
